server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://10.10.10.106:3306/romantic_spring_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: ipos
    password: hongjipos@2016
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password:


  thymeleaf:
    cache: false
    mode: HTML
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB


mybatis:
  type-aliases-package: com.honji.recommendation


mybatis-plus:
    # 支持统配符 * 或者 ; 分割
    typeEnumsPackage: com.honji.recommendation.enums
    configuration:
      default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

wx:
  miniapp:
    configs:
      - appid: wxfd6220e7603a31f8
        secret: 5df7cc13f54a34cf4ab8006418cb7ac4
        token: #微信小程序消息服务器配置的token
        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON

logging:
  file: logs/recommendation-wechat.log
  level:
    com.honji.recommendation.mapper: debug
    root: INFO
